### ISSUE TITLE
Description/Details of the MEC update into NS-3

### ISSUE THREAD

**Issue by WaqasRahman** [mmajanen/ns3-MEC#1]
Greetings !!!

Thankyou for uploading your work here. Is it possible for you to add some details regarding what changes did you add to the ns-3.26 release and the LTE module?

**Comment by mmajanen** [comment]
The LTE model is enhanced by adding a MEC server next to eNB or on the SGW/PGW node.
I have tried to mark my changes in the source code with comments containing my initials 'MiM'. Changes are at least in src/lte/model/epc-enb-application.cc, mec-server-application.cc and src/lte/helper/point-to-point-epc-helper.cc.
An example simulation script is in scratch/lte-mec.cc, which is a good starting point for testing.
There are some limitations/TODOs, e.g., only one MEC is currently supported.
